if(NOT DEFINED TEST_MPI_F08)
  message(FATAL_ERROR "TEST_MPI_F08 must be ON or OFF")
endif()

set(MPI_Fortran_HAVE_F08_MODULE "${TEST_MPI_F08}")
if(DEFINED TEST_MPI_FORTRAN_COMPILER)
  set(MPI_Fortran_COMPILER "${TEST_MPI_FORTRAN_COMPILER}")
else()
  set(MPI_Fortran_COMPILER "${CMAKE_COMMAND}")
endif()
if(DEFINED TEST_MPIEXEC_EXECUTABLE)
  set(MPIEXEC_EXECUTABLE "${TEST_MPIEXEC_EXECUTABLE}")
else()
  set(MPIEXEC_EXECUTABLE "${CMAKE_COMMAND}")
endif()
set(CMAKE_Fortran_COMPILER "test-gfortran")
include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/RequireMpiF08.cmake")
pelef_require_mpi_f08()
