program pelef3d
  use precision_mod, only: dp
  use constants_mod, only: pelef_version
  use state_indices_mod, only: &
    irho, imx, imy, imz, iet, ncons, nprim, qrho
  use state_conversion_mod, only: conserved_to_primitive
  use mesh_3d_mod, only: uniform_cell_centers_3d
  use simulation_config_3d_mod, only: &
    simulation_config_3d, entropy_wave_3d_config, read_configuration_3d
  use entropy_wave_3d_problem_mod, only: &
    initialize_entropy_wave_3d, entropy_wave_3d_primitive
  use finite_volume_3d_mod, only: &
    compute_euler_cfl_timestep_3d, advance_euler_ssprk2_3d
  use diagnostics_3d_mod, only: &
    integrated_conserved_quantities_3d, primitive_extrema_3d
  use csv_io_3d_mod, only: write_solution_csv_3d
  implicit none

  type(simulation_config_3d) :: simulation
  type(entropy_wave_3d_config) :: wave
  character(len=1024) :: input_path, message
  real(dp), allocatable :: x(:), y(:), z(:), conserved(:, :, :, :)
  real(dp) :: dx, dy, dz, time, dt, density_l1_error
  real(dp) :: minimum_density, maximum_density
  real(dp) :: minimum_pressure, maximum_pressure
  real(dp) :: initial_totals(ncons), final_totals(ncons)
  real(dp) :: primitive(nprim), exact_primitive(nprim)
  logical :: ok, cell_ok
  integer :: argument_count, step, i, j, k

  argument_count = command_argument_count()
  if (argument_count /= 1) then
    write(*, '(a)') "Usage: pelef3d <input.nml>"
    error stop 2
  end if

  call get_command_argument(1, input_path)
  call read_configuration_3d( &
    trim(input_path), simulation, wave, ok, message)
  if (.not. ok) then
    write(*, '(a)') trim(message)
    error stop 2
  end if

  allocate(x(simulation%nx), y(simulation%ny), z(simulation%nz))
  allocate(conserved(ncons, simulation%nx, simulation%ny, simulation%nz))
  call uniform_cell_centers_3d( &
    simulation%nx, simulation%ny, simulation%nz, &
    simulation%x_min, simulation%x_max, &
    simulation%y_min, simulation%y_max, &
    simulation%z_min, simulation%z_max, x, y, z, dx, dy, dz)
  call initialize_entropy_wave_3d( &
    x, y, z, simulation%nx, simulation%ny, simulation%nz, &
    simulation%x_min, simulation%x_max, &
    simulation%y_min, simulation%y_max, &
    simulation%z_min, simulation%z_max, &
    simulation%gamma, wave, conserved, ok)
  if (.not. ok) error stop "Failed to initialize 3D entropy wave"

  call integrated_conserved_quantities_3d( &
    conserved, simulation%nx, simulation%ny, simulation%nz, &
    dx, dy, dz, initial_totals)

  write(*, '(a)') "PeleF " // pelef_version // " 3D"
  write(*, '(a,1x,a)') "Input:", trim(input_path)
  write(*, '(a,i0,a,i0,a,i0)') &
    "Grid: nx=", simulation%nx, ", ny=", simulation%ny, &
    ", nz=", simulation%nz
  write(*, '(a,es12.5,a,es12.5,a,es12.5)') &
    "Spacing: dx=", dx, ", dy=", dy, ", dz=", dz
  write(*, '(a,1x,a)') "Boundary condition:", &
    trim(simulation%boundary_condition)
  write(*, '(a,1x,a)') "Riemann solver:", trim(simulation%riemann_solver)

  time = 0.0_dp
  step = 0
  do while (time < simulation%final_time)
    if (step >= simulation%max_steps) then
      error stop "Maximum step count reached before final_time"
    end if
    call compute_euler_cfl_timestep_3d( &
      conserved, simulation%nx, simulation%ny, simulation%nz, &
      dx, dy, dz, simulation%gamma, simulation%cfl, dt, ok)
    if (.not. ok) error stop "Failed to compute a positive 3D CFL timestep"

    dt = min(dt, simulation%final_time - time)
    call advance_euler_ssprk2_3d( &
      conserved, simulation%nx, simulation%ny, simulation%nz, &
      dx, dy, dz, dt, simulation%gamma, simulation%riemann_solver, ok)
    if (.not. ok) error stop "Non-physical state generated by 3D Euler update"
    time = time + dt
    step = step + 1
  end do

  call integrated_conserved_quantities_3d( &
    conserved, simulation%nx, simulation%ny, simulation%nz, &
    dx, dy, dz, final_totals)
  call primitive_extrema_3d( &
    conserved, simulation%nx, simulation%ny, simulation%nz, &
    simulation%gamma, minimum_density, maximum_density, &
    minimum_pressure, maximum_pressure, ok)
  if (.not. ok) error stop "Final 3D state is not physical"

  density_l1_error = 0.0_dp
  do k = 1, simulation%nz
    do j = 1, simulation%ny
      do i = 1, simulation%nx
        call conserved_to_primitive( &
          conserved(:, i, j, k), simulation%gamma, primitive, cell_ok)
        if (.not. cell_ok) error stop "Invalid final 3D cell"
        call entropy_wave_3d_primitive( &
          x(i), y(j), z(k), time, &
          simulation%x_min, simulation%x_max, &
          simulation%y_min, simulation%y_max, &
          simulation%z_min, simulation%z_max, &
          wave, exact_primitive, cell_ok)
        if (.not. cell_ok) error stop "Failed to evaluate exact 3D wave"
        density_l1_error = density_l1_error + &
          abs(primitive(qrho) - exact_primitive(qrho))
      end do
    end do
  end do
  density_l1_error = density_l1_error / &
    real(simulation%nx * simulation%ny * simulation%nz, dp)

  call write_solution_csv_3d( &
    trim(simulation%output_file), x, y, z, conserved, simulation%nx, &
    simulation%ny, simulation%nz, simulation%gamma, ok, message)
  if (.not. ok) then
    write(*, '(a)') trim(message)
    error stop 3
  end if

  write(*, '(a,i0)') "Completed steps: ", step
  write(*, '(a,es24.16)') "Final time: ", time
  write(*, '(a,es24.16)') "Density L1 error: ", density_l1_error
  write(*, '(a,es24.16)') "Minimum density: ", minimum_density
  write(*, '(a,es24.16)') "Maximum density: ", maximum_density
  write(*, '(a,es24.16)') "Minimum pressure: ", minimum_pressure
  write(*, '(a,es24.16)') "Maximum pressure: ", maximum_pressure
  write(*, '(a,es24.16)') &
    "Mass change: ", final_totals(irho) - initial_totals(irho)
  write(*, '(a,es24.16)') &
    "X-momentum change: ", final_totals(imx) - initial_totals(imx)
  write(*, '(a,es24.16)') &
    "Y-momentum change: ", final_totals(imy) - initial_totals(imy)
  write(*, '(a,es24.16)') &
    "Z-momentum change: ", final_totals(imz) - initial_totals(imz)
  write(*, '(a,es24.16)') &
    "Energy change: ", final_totals(iet) - initial_totals(iet)
  write(*, '(a,1x,a)') "Output:", trim(simulation%output_file)
end program pelef3d
