program pelef
  use precision_mod, only: dp
  use constants_mod, only: pelef_version
  use state_indices_mod, only: irho, imx, iet, ncons
  use mesh_mod, only: uniform_cell_centers
  use simulation_config_mod, only: &
    simulation_config, sod_config, shu_osher_config, read_configuration
  use sod_problem_mod, only: initialize_sod_problem
  use shu_osher_problem_mod, only: initialize_shu_osher_problem
  use time_integrator_mod, only: compute_cfl_timestep, advance_hydro_step
  use diagnostics_mod, only: integrated_conserved_quantities, primitive_extrema
  use csv_io_mod, only: write_solution_csv
  implicit none

  type(simulation_config) :: simulation
  type(sod_config) :: sod
  type(shu_osher_config) :: shu_osher
  character(len=1024) :: input_path
  character(len=1024) :: message
  real(dp), allocatable :: x(:), conserved(:, :)
  real(dp) :: dx, time, dt, minimum_density, minimum_pressure
  real(dp) :: initial_totals(ncons), final_totals(ncons)
  logical :: ok
  integer :: argument_count, step

  argument_count = command_argument_count()
  if (argument_count /= 1) then
    write(*, '(a)') "Usage: pelef <input.nml>"
    error stop 2
  end if

  call get_command_argument(1, input_path)
  call read_configuration( &
    trim(input_path), simulation, sod, shu_osher, ok, message)
  if (.not. ok) then
    write(*, '(a)') trim(message)
    error stop 2
  end if

  allocate(x(simulation%nx))
  allocate(conserved(ncons, 0:simulation%nx + 1))

  call uniform_cell_centers( &
    simulation%nx, simulation%x_min, simulation%x_max, x, dx)

  select case (trim(simulation%problem))
  case ("sod")
    call initialize_sod_problem( &
      x, simulation%nx, simulation%gamma, sod, conserved, ok)
  case ("shu_osher")
    call initialize_shu_osher_problem( &
      x, simulation%nx, simulation%gamma, shu_osher, conserved, ok)
  case default
    ok = .false.
  end select
  if (.not. ok) error stop "Failed to initialize selected problem"

  call integrated_conserved_quantities( &
    conserved, simulation%nx, dx, initial_totals)

  write(*, '(a)') "PeleF " // pelef_version
  write(*, '(a,1x,a)') "Input:", trim(input_path)
  write(*, '(a,1x,a)') "Problem:", trim(simulation%problem)
  write(*, '(a,i0,a,es12.5)') "Grid: nx=", simulation%nx, ", dx=", dx
  write(*, '(a,1x,a)') "Reconstruction:", trim(simulation%reconstruction)
  if (trim(simulation%reconstruction) /= "pcm") then
    write(*, '(a,1x,a)') "Limiter:", trim(simulation%limiter)
  end if
  write(*, '(a,1x,a)') "Riemann solver:", trim(simulation%riemann_solver)
  write(*, '(a,1x,a)') "Boundary:", trim(simulation%boundary_condition)

  time = 0.0_dp
  step = 0
  do while (time < simulation%final_time)
    if (step >= simulation%max_steps) then
      error stop "Maximum step count reached before final_time"
    end if
    call compute_cfl_timestep( &
      conserved, simulation%nx, dx, simulation%gamma, simulation%cfl, dt, ok)
    if (.not. ok) error stop "Failed to compute a positive CFL timestep"

    dt = min(dt, simulation%final_time - time)
    call advance_hydro_step( &
      conserved, simulation%nx, dx, dt, simulation%gamma, ok, &
      reconstruction=simulation%reconstruction, limiter=simulation%limiter, &
      boundary_condition=simulation%boundary_condition, &
      riemann_solver=simulation%riemann_solver)
    if (.not. ok) error stop "Non-physical state generated by hydro update"

    time = time + dt
    step = step + 1
  end do

  call integrated_conserved_quantities( &
    conserved, simulation%nx, dx, final_totals)
  call primitive_extrema( &
    conserved, simulation%nx, simulation%gamma, minimum_density, &
    minimum_pressure, ok)
  if (.not. ok) error stop "Final state is not physical"

  call write_solution_csv( &
    trim(simulation%output_file), x, conserved, simulation%nx, &
    simulation%gamma, ok, message)
  if (.not. ok) then
    write(*, '(a)') trim(message)
    error stop 3
  end if

  write(*, '(a,i0)') "Completed steps: ", step
  write(*, '(a,es24.16)') "Final time: ", time
  write(*, '(a,es24.16)') "Minimum density: ", minimum_density
  write(*, '(a,es24.16)') "Minimum pressure: ", minimum_pressure
  write(*, '(a,es24.16)') &
    "Mass change: ", final_totals(irho) - initial_totals(irho)
  write(*, '(a,es24.16)') &
    "Momentum change: ", final_totals(imx) - initial_totals(imx)
  write(*, '(a,es24.16)') &
    "Energy change: ", final_totals(iet) - initial_totals(iet)
  write(*, '(a,1x,a)') "Output:", trim(simulation%output_file)
end program pelef
