program pelef2d
  use precision_mod, only: dp
  use constants_mod, only: pelef_version
  use state_indices_mod, only: irho, imx, imy, iet, ncons
  use mesh_2d_mod, only: uniform_cell_centers_2d
  use simulation_config_2d_mod, only: &
    simulation_config_2d, isentropic_vortex_config, read_configuration_2d
  use isentropic_vortex_problem_mod, only: initialize_isentropic_vortex
  use ctu_2d_mod, only: compute_cfl_timestep_2d, advance_ctu_2d
  use diagnostics_2d_mod, only: &
    integrated_conserved_quantities_2d, primitive_extrema_2d
  use csv_io_2d_mod, only: write_solution_csv_2d
  implicit none

  type(simulation_config_2d) :: simulation
  type(isentropic_vortex_config) :: vortex
  character(len=1024) :: input_path, message
  real(dp), allocatable :: x(:), y(:), conserved(:, :, :)
  real(dp) :: dx, dy, time, dt, step_theta, minimum_theta
  real(dp) :: minimum_density, maximum_density
  real(dp) :: minimum_pressure, maximum_pressure
  real(dp) :: initial_totals(ncons), final_totals(ncons)
  logical :: ok
  integer :: argument_count, step

  argument_count = command_argument_count()
  if (argument_count /= 1) then
    write(*, '(a)') "Usage: pelef2d <input.nml>"
    error stop 2
  end if

  call get_command_argument(1, input_path)
  call read_configuration_2d( &
    trim(input_path), simulation, vortex, ok, message)
  if (.not. ok) then
    write(*, '(a)') trim(message)
    error stop 2
  end if

  allocate(x(simulation%nx), y(simulation%ny))
  allocate(conserved(ncons, simulation%nx, simulation%ny))

  call uniform_cell_centers_2d( &
    simulation%nx, simulation%ny, simulation%x_min, simulation%x_max, &
    simulation%y_min, simulation%y_max, x, y, dx, dy)
  call initialize_isentropic_vortex( &
    x, y, simulation%nx, simulation%ny, simulation%x_min, &
    simulation%x_max, simulation%y_min, simulation%y_max, &
    simulation%gamma, vortex, conserved, ok)
  if (.not. ok) error stop "Failed to initialize isentropic vortex"

  call integrated_conserved_quantities_2d( &
    conserved, simulation%nx, simulation%ny, dx, dy, initial_totals)

  write(*, '(a)') "PeleF " // pelef_version // " 2D"
  write(*, '(a,1x,a)') "Input:", trim(input_path)
  write(*, '(a,i0,a,i0)') &
    "Grid: nx=", simulation%nx, ", ny=", simulation%ny
  write(*, '(a,es12.5,a,es12.5)') "Spacing: dx=", dx, ", dy=", dy
  write(*, '(a,1x,a)') "Limiter:", trim(simulation%limiter)
  write(*, '(a,1x,a)') "Riemann solver:", trim(simulation%riemann_solver)
  write(*, '(a,l1)') &
    "Transverse correction: ", simulation%use_transverse_correction

  time = 0.0_dp
  step = 0
  minimum_theta = 1.0_dp
  do while (time < simulation%final_time)
    if (step >= simulation%max_steps) then
      error stop "Maximum step count reached before final_time"
    end if

    call compute_cfl_timestep_2d( &
      conserved, simulation%nx, simulation%ny, dx, dy, simulation%gamma, &
      simulation%cfl, dt, ok)
    if (.not. ok) error stop "Failed to compute a positive 2D CFL timestep"

    dt = min(dt, simulation%final_time - time)
    call advance_ctu_2d( &
      conserved, simulation%nx, simulation%ny, dx, dy, dt, &
      simulation%gamma, simulation%limiter, simulation%riemann_solver, &
      simulation%use_transverse_correction, ok, step_theta)
    if (.not. ok) error stop "Non-physical state generated by 2D CTU update"

    minimum_theta = min(minimum_theta, step_theta)
    time = time + dt
    step = step + 1
  end do

  call integrated_conserved_quantities_2d( &
    conserved, simulation%nx, simulation%ny, dx, dy, final_totals)
  call primitive_extrema_2d( &
    conserved, simulation%nx, simulation%ny, simulation%gamma, &
    minimum_density, maximum_density, minimum_pressure, maximum_pressure, ok)
  if (.not. ok) error stop "Final 2D state is not physical"

  call write_solution_csv_2d( &
    trim(simulation%output_file), x, y, conserved, simulation%nx, &
    simulation%ny, simulation%gamma, ok, message)
  if (.not. ok) then
    write(*, '(a)') trim(message)
    error stop 3
  end if

  write(*, '(a,i0)') "Completed steps: ", step
  write(*, '(a,es24.16)') "Final time: ", time
  write(*, '(a,es24.16)') "Minimum density: ", minimum_density
  write(*, '(a,es24.16)') "Maximum density: ", maximum_density
  write(*, '(a,es24.16)') "Minimum pressure: ", minimum_pressure
  write(*, '(a,es24.16)') "Maximum pressure: ", maximum_pressure
  write(*, '(a,es24.16)') "Minimum transverse theta: ", minimum_theta
  write(*, '(a,es24.16)') &
    "Mass change: ", final_totals(irho) - initial_totals(irho)
  write(*, '(a,es24.16)') &
    "X-momentum change: ", final_totals(imx) - initial_totals(imx)
  write(*, '(a,es24.16)') &
    "Y-momentum change: ", final_totals(imy) - initial_totals(imy)
  write(*, '(a,es24.16)') &
    "Energy change: ", final_totals(iet) - initial_totals(iet)
  write(*, '(a,1x,a)') "Output:", trim(simulation%output_file)
end program pelef2d
